start moc.exe mainwindow.h -o gen\moc_mainwindow.cpp
start moc.exe myCameraView.h -o gen\moc_myCameraView.cpp
start moc.exe recordWindow.h -o gen\moc_recordWindow.cpp
start moc.exe replayWindow.h -o gen\moc_replayWindow.cpp
start moc.exe calibrateWindow.h -o gen\moc_calibrateWindow.cpp
start moc.exe stereoCalWindow.h -o gen\moc_stereoCalWindow.cpp
start moc.exe manualWindow.h -o gen\moc_manualWindow.cpp
start moc.exe measureMarkersWindows.h -o gen\moc_measureMarkersWindows.cpp
start moc.exe markerDefineWindow.h -o gen\moc_markerDefineWindow.cpp
start moc.exe trackingWindow.h -o gen\moc_trackingWindow.cpp